---

  #
  # install wpa_supplicant
  #
  - name: Install wpa_supplicant
    become: yes
    apt:
      name: wpasupplicant
      update_cache: yes
      cache_valid_time: "{{ wifi_apt_cache_valid_time }}"

  #
  # configure wpa_supplicant
  #
  - name: Configure wpa_supplicant
    become: yes
    template:
      src: wpa_supplicant.conf.j2
      dest: /etc/wpa_supplicant/wpa_supplicant.conf
      backup: yes
    notify: Restart Networking
